hosts:
  dev: # branch to deploy, should be enabled in deploy.yml
    hostname: dev-host # hostname of server
    remote_user: dev-user # username for connect
    deploy_path: ~/dev-deploy # path to deploy on server | default: ~/deploy
    repo_path: src # folder in repository that will be used as document root | default: src
    asset_locales: en_US # languages of Magento2 to deploy | default: en_US en_IE

    # if there's a plus symbol before variable name - it extends global value,
    # otherwise it simply overrides
    +symlinks: # symlinks, which should be created after deploy | default: pub/pub: .
      pub/app: ../app
      pub/dev: ../dev

    +shared_files: # shared files between releases | default: app/etc/env.php
      - app/etc/di.xml
      - app/.htaccess

    shared_dirs: # shared directories between releases | default: pub/media, var/log
      - var/composer_home

  test:
    hostname: test-host
    remote_user: test-user

  master:
    hostname: master-host
    remote_user: master-user
